const SHARED_WALLET_RU = {
  label: 'Кошелёк',
  title: 'Кошелёк',
  amount: '15 000 ₽',
  note: 'Нет бонусов',
}

const SHARED_WALLET_EN = {
  label: 'Wallet',
  title: 'Wallet',
  amount: '15 000 ₽',
  note: 'No bonuses',
}

const CABINET_STAGE_CONTENT_RU = {
  header: {
    topLinks: [
      { label: 'Для бизнеса' },
      { label: 'Карьера в Авито' },
      { label: 'Помощь' },
      { label: 'Каталоги', caret: true },
      { label: '#яПомогаю' },
    ],
    categoryLinks: [
      { label: 'Авто' },
      { label: 'Недвижимость' },
      { label: 'Работа' },
      { label: 'Услуги' },
      { label: 'Ещё' },
    ],
    primaryAction: '+ Разместить объявление',
    secondaryAction: 'Мои объявления',
    actionIcons: [
      { icon: 'favorite' },
      { icon: 'bell', badge: 2 },
      { icon: 'chat', badge: 2 },
      { icon: 'cart' },
    ],
    avatar: {
      variant: 'cluster',
    },
  },
  sidebar: {
    profile: {
      title: 'ПерфАгентство',
      rating: '4,9',
      reviews: '1 отзыв',
    },
    wallet: {
      label: SHARED_WALLET_RU.label,
      amount: SHARED_WALLET_RU.amount,
      note: SHARED_WALLET_RU.note,
      action: 'Пополнить',
    },
    navigation: [
      { icon: 'stats', label: 'Мои объявления', href: '/my-ads', aliases: ['/'] },
      { icon: 'chat', label: 'Сообщения', href: '/messages', badge: 2 },
      { icon: 'star', label: 'Клиенты', href: '/clients' },
      { icon: 'ruble', label: 'Финансы', href: '/finance' },
      { icon: 'work', label: 'Сотрудники', href: '/employees' },
      { icon: 'statistics', label: 'Аналитика спроса', href: '/demand-analytics' },
      { icon: 'diagram', label: 'Статистика', href: '/statistics' },
      { icon: 'wallet', label: 'Кошелёк', href: '/wallet', caret: true },
      { icon: 'shield', label: 'Для бизнеса', href: '/business' },
      { icon: 'profile', label: 'Профиль и настройки', href: '/profile', caret: true },
    ],
  },
  content: {
    pageTitle: 'Мои объявления',
    promoBanner: {
      title: 'Продавайте с примеркой',
      description: 'Это может привлечь покупателей',
      actionLabel: 'Подробнее',
    },
    featurePromo: {
      icon: '%',
      title: 'Скидки и акции',
      description: 'Настройте для покупателей',
      badge: 'Новое',
    },
    tabs: [
      { label: 'Ждут действий', count: 93, active: true },
      { label: 'Архив', count: 3, active: false },
    ],
    toolbar: {
      checkboxLabel: 'Выбрать объявления',
      sortLabel: 'Сортировка',
    },
    ads: [
      {
        title: 'Мини-экскаватор Aolite WJ10, 2021',
        price: '4 461 525 ₽ с НДС',
        meta: 'Москва, Никольская ул., 5/1с2',
        location: 'Площадь революции, 200 м',
        state: 'Не оплачено',
        action: 'Оплатить размещение',
        tone: 'mint',
        views: 0,
        favorites: 0,
        contacts: 0,
        chats: 'Нет новых чатов',
        moreLabel: 'Ещё',
      },
      {
        title: 'Ученик автомеханика',
        price: 'Зарплата не указана',
        meta: 'Москва, Никольская ул., 5/1с2',
        location: 'Площадь революции, 300 м',
        state: 'Истёк срок размещения',
        action: 'Опубликовать',
        tone: 'sand',
        views: 0,
        favorites: 0,
        contacts: 0,
        chats: 'Нет новых чатов',
        moreLabel: 'Ещё',
      },
      {
        title: 'Продавец зарплата 10000',
        price: '1 000 – 10 000 ₽',
        meta: 'Москва, Ипатьевский пер., 4-10с1',
        location: 'Китай-город, 300 м',
        state: 'Истёк срок размещения',
        action: 'Опубликовать',
        tone: 'rose',
        views: 0,
        favorites: 0,
        contacts: 0,
        chats: 'Нет новых чатов',
        moreLabel: 'Ещё',
      },
      {
        title: 'Тест',
        price: 'до 500 000 ₽',
        meta: 'Москва, Лесная ул., 7',
        location: 'Белорусская, 200 м',
        state: 'Отклонено: Некорректное название',
        action: 'Исправить',
        tone: 'sky',
        views: 1,
        favorites: 0,
        contacts: 0,
        chats: 'Нет новых чатов',
        moreLabel: 'Ещё',
      },
    ],
  },
  floatingChat: {
    label: 'Сообщения',
    count: 2,
  },
  footer: {
    links: [
      { label: 'Помощь' },
      { label: 'Безопасность' },
      { label: 'Реклама на сайте' },
      { label: 'О компании' },
      { label: 'Карьера' },
      { label: 'Авито Журнал' },
      { label: 'Блог' },
      { label: '#яПомогаю' },
      { label: 'Приложение' },
      { label: 'Займы онлайн' },
      { label: 'Карта сайта' },
      { label: 'Свежие объявления' },
    ],
    featureTogglesLabel: 'Панель фича тогглов',
    showcaseLabel: 'Витрина',
    legalText:
      'Авито — сайт объявлений России. Политика конфиденциальности и правила платформы применяются ко всем разделам кабинета.',
    socialLinks: [
      { label: 'VK', shortLabel: 'VK' },
      { label: 'OK', shortLabel: 'OK' },
      { label: 'Telegram', shortLabel: 'TG' },
      { label: 'Rutube', shortLabel: 'R' },
      { label: 'Pulse', shortLabel: 'P' },
    ],
  },
  finance: {
    title: 'Финансы',
    failedAmountHint: 'Операция не выполнена. Проверьте данные и попробуйте снова.',
    newContent: {
      agencyCard: {
        title: 'Баланс агентства',
        description: 'Распределяйте деньги между сотрудниками',
        amount: '125 000 ₽',
        note: 'Из них в обработке 18 000 ₽',
        actionLabel: 'Перевести',
      },
      walletCard: {
        title: SHARED_WALLET_RU.title,
        description: 'Для оплаты услуг продвижения',
        amount: SHARED_WALLET_RU.amount,
        note: SHARED_WALLET_RU.note,
        actionLabel: 'Оплатить',
      },
      postpayCard: {
        title: 'Постоплата',
        description: 'Деньги поступят на кошелёк',
        amount: '1 500 000 ₽',
        note: 'Получено 0 из 1 500 000 ₽',
        actionLabel: 'Запросить',
        requestMoreLabel: 'Запросить ещё',
        returnLabel: 'Вернуть',
        minRequestAmount: 5000,
        defaultRequestAmount: 1000000,
        progress: 0,
      },
      operationTabs: [
        { key: 'all', label: 'Все' },
        { key: 'agency', label: 'Баланс агентства' },
        { key: 'wallet', label: 'Кошелёк' },
      ],
    },
    newContentV2: {
      agencyCard: {
        title: 'Баланс агентства',
        amount: '125 000 ₽',
        note: 'Из них в обработке 18 000 ₽',
        actionLabel: 'Перевести',
      },
      walletCard: {
        title: SHARED_WALLET_RU.title,
        amount: '25 000 ₽',
        note: SHARED_WALLET_RU.note,
        actionLabel: 'Оплатить',
        topUpLabel: 'Пополнить',
      },
    },
    balances: [
      {
        label: 'Баланс агентства',
        amount: '10 125 000,00 ₽',
        note: 'Из них в обработке 18 000 ₽',
        selected: true,
      },
      {
        label: SHARED_WALLET_RU.title,
        amount: SHARED_WALLET_RU.amount,
        note: SHARED_WALLET_RU.note,
        selected: false,
      },
    ],
    periodLabel: '13.03.2025 — 19.03.2025',
    datePicker: {
      presets: [
        { label: 'Эта неделя', active: true, start: '2025-03-13', end: '2025-03-19' },
        { label: 'Прошлая неделя', start: '2025-03-06', end: '2025-03-12' },
        { label: 'Этот месяц', start: '2025-03-01', end: '2025-03-31' },
        { label: 'Предыдущий месяц', start: '2025-02-01', end: '2025-02-28' },
        { label: 'Этот квартал', start: '2025-01-01', end: '2025-03-31' },
        { label: 'Предыдущий квартал', start: '2024-10-01', end: '2024-12-31' },
        { label: 'Этот год', start: '2025-01-01', end: '2025-12-31' },
      ],
      weekdays: ['Пн', 'Вт', 'Ср', 'Чт', 'Пт', 'Сб', 'Вс'],
      timezoneLabel: 'UTC+3 (МСК)',
      startDateLabel: '13.03.25',
      endDateLabel: '19.03.25',
      applyLabel: 'Применить',
    },
    columns: ['Дата и время', 'Сумма', 'Клиент', 'Операции'],
    transactions: [
      {
        date: '05.08.2025, 19:20',
        amount: '−18 000 ₽',
        amountTone: 'negative',
        bucket: 'agency',
        client: '«Альфа Групп»',
        operation: 'Списание на клиента ID4572854289',
      },
      {
        date: '05.08.2025, 17:09',
        amount: '−12 900 ₽',
        amountTone: 'negative',
        bucket: 'agency',
        client: '«СмартМаркет»',
        operation: 'Списание на клиента ID4572854289',
      },
      {
        date: '04.08.2025, 11:20',
        amount: '+85 000 ₽',
        amountTone: 'positive',
        bucket: 'wallet',
        client: '—',
        operation: 'Пополнение баланса',
      },
      {
        date: '04.08.2025, 09:06',
        amount: '−9 750 ₽',
        amountTone: 'negative-soft',
        bucket: 'agency',
        client: '«ЭкоДом»',
        operation: 'Списание на клиента ID4572854289',
      },
      {
        date: '03.08.2025, 11:20',
        amount: '+60 000 ₽',
        amountTone: 'positive',
        bucket: 'wallet',
        client: '—',
        operation: 'Пополнение баланса',
      },
    ],
    loadMoreLabel: 'Загрузить ещё',
  },
}

const CABINET_STAGE_CONTENT_EN = {
  header: {
    topLinks: [
      { label: 'For business' },
      { label: 'Careers at Avito' },
      { label: 'Help' },
      { label: 'Catalogs', caret: true },
      { label: '#WeHelp' },
    ],
    categoryLinks: [
      { label: 'Cars' },
      { label: 'Real estate' },
      { label: 'Jobs' },
      { label: 'Services' },
      { label: 'More' },
    ],
    primaryAction: '+ Post ad',
    secondaryAction: 'My ads',
    actionIcons: [
      { icon: 'favorite' },
      { icon: 'bell', badge: 2 },
      { icon: 'chat', badge: 2 },
      { icon: 'cart' },
    ],
    avatar: {
      variant: 'cluster',
    },
  },
  sidebar: {
    profile: {
      title: 'ПерфАгентство',
      rating: '4,9',
      reviews: '1 review',
    },
    wallet: {
      label: SHARED_WALLET_EN.label,
      amount: SHARED_WALLET_EN.amount,
      note: SHARED_WALLET_EN.note,
      action: 'Top up',
    },
    navigation: [
      { icon: 'stats', label: 'My ads', href: '/my-ads', aliases: ['/'] },
      { icon: 'chat', label: 'Messages', href: '/messages', badge: 2 },
      { icon: 'star', label: 'Clients', href: '/clients' },
      { icon: 'ruble', label: 'Finance', href: '/finance' },
      { icon: 'work', label: 'Employees', href: '/employees' },
      { icon: 'statistics', label: 'Demand analytics', href: '/demand-analytics' },
      { icon: 'diagram', label: 'Statistics', href: '/statistics' },
      { icon: 'wallet', label: 'Wallet', href: '/wallet', caret: true },
      { icon: 'shield', label: 'For business', href: '/business' },
      { icon: 'profile', label: 'Profile & settings', href: '/profile', caret: true },
    ],
  },
  content: {
    pageTitle: 'My ads',
    promoBanner: {
      title: 'Sell with fitting',
      description: 'This may attract more buyers',
      actionLabel: 'Learn more',
    },
    featurePromo: {
      icon: '%',
      title: 'Discounts and promotions',
      description: 'Set them up for buyers',
      badge: 'New',
    },
    tabs: [
      { label: 'Need action', count: 93, active: true },
      { label: 'Archive', count: 3, active: false },
    ],
    toolbar: {
      checkboxLabel: 'Select ads',
      sortLabel: 'Sort',
    },
    ads: [
      {
        title: 'Mini excavator Aolite WJ10, 2021',
        price: '4 461 525 ₽ incl. VAT',
        meta: 'Moscow, Nikolskaya St., 5/1 bld. 2',
        location: 'Ploshchad Revolyutsii, 200 m',
        state: 'Unpaid',
        action: 'Pay for listing',
        tone: 'mint',
        views: 0,
        favorites: 0,
        contacts: 0,
        chats: 'No new chats',
        moreLabel: 'More',
      },
      {
        title: 'Junior auto mechanic',
        price: 'Salary not specified',
        meta: 'Moscow, Nikolskaya St., 5/1 bld. 2',
        location: 'Ploshchad Revolyutsii, 300 m',
        state: 'Listing expired',
        action: 'Publish',
        tone: 'sand',
        views: 0,
        favorites: 0,
        contacts: 0,
        chats: 'No new chats',
        moreLabel: 'More',
      },
      {
        title: 'Salesperson salary 10000',
        price: '1 000 – 10 000 ₽',
        meta: 'Moscow, Ipatyevsky Ln., 4-10 bld. 1',
        location: 'Kitay-Gorod, 300 m',
        state: 'Listing expired',
        action: 'Publish',
        tone: 'rose',
        views: 0,
        favorites: 0,
        contacts: 0,
        chats: 'No new chats',
        moreLabel: 'More',
      },
      {
        title: 'Test',
        price: 'up to 500 000 ₽',
        meta: 'Moscow, Lesnaya St., 7',
        location: 'Belorusskaya, 200 m',
        state: 'Rejected: Incorrect title',
        action: 'Fix',
        tone: 'sky',
        views: 1,
        favorites: 0,
        contacts: 0,
        chats: 'No new chats',
        moreLabel: 'More',
      },
    ],
  },
  floatingChat: {
    label: 'Messages',
    count: 2,
  },
  footer: {
    links: [
      { label: 'Help' },
      { label: 'Safety' },
      { label: 'Advertising' },
      { label: 'About' },
      { label: 'Careers' },
      { label: 'Avito Journal' },
      { label: 'Blog' },
      { label: '#WeHelp' },
      { label: 'App' },
      { label: 'Loans online' },
      { label: 'Sitemap' },
      { label: 'Latest ads' },
    ],
    featureTogglesLabel: 'Feature toggles panel',
    showcaseLabel: 'Showcase',
    legalText:
      'Avito is a classifieds platform in Russia. Privacy policy and platform rules apply to all cabinet sections.',
    socialLinks: [
      { label: 'VK', shortLabel: 'VK' },
      { label: 'OK', shortLabel: 'OK' },
      { label: 'Telegram', shortLabel: 'TG' },
      { label: 'Rutube', shortLabel: 'R' },
      { label: 'Pulse', shortLabel: 'P' },
    ],
  },
  finance: {
    title: 'Finance',
    failedAmountHint: 'The operation failed. Check the data and try again.',
    newContent: {
      agencyCard: {
        title: 'Agency balance',
        description: 'Distribute money between employees',
        amount: '125 000 ₽',
        note: '18 000 ₽ is being processed',
        actionLabel: 'Transfer',
      },
      walletCard: {
        title: SHARED_WALLET_EN.title,
        description: 'Used to pay for promotion services',
        amount: SHARED_WALLET_EN.amount,
        note: SHARED_WALLET_EN.note,
        actionLabel: 'Pay',
      },
      postpayCard: {
        title: 'Postpay',
        description: 'Funds will be credited to the wallet',
        amount: '1 500 000 ₽',
        note: 'Received 0 of 1 500 000 ₽',
        actionLabel: 'Request',
        requestMoreLabel: 'Request more',
        returnLabel: 'Revert',
        minRequestAmount: 5000,
        defaultRequestAmount: 1000000,
        progress: 0,
      },
      operationTabs: [
        { key: 'all', label: 'All' },
        { key: 'agency', label: 'Agency balance' },
        { key: 'wallet', label: 'Wallet' },
      ],
    },
    newContentV2: {
      agencyCard: {
        title: 'Agency balance',
        amount: '125 000 ₽',
        note: '18 000 ₽ is being processed',
        actionLabel: 'Transfer',
      },
      walletCard: {
        title: SHARED_WALLET_EN.title,
        amount: '25 000 ₽',
        note: SHARED_WALLET_EN.note,
        actionLabel: 'Pay',
        topUpLabel: 'Top up',
      },
    },
    balances: [
      {
        label: 'Agency balance',
        amount: '10 125 000,00 ₽',
        note: '18 000 ₽ is being processed',
        selected: true,
      },
      {
        label: SHARED_WALLET_EN.title,
        amount: SHARED_WALLET_EN.amount,
        note: SHARED_WALLET_EN.note,
        selected: false,
      },
    ],
    periodLabel: '13.03.2025 — 19.03.2025',
    datePicker: {
      presets: [
        { label: 'This week', active: true, start: '2025-03-13', end: '2025-03-19' },
        { label: 'Last week', start: '2025-03-06', end: '2025-03-12' },
        { label: 'This month', start: '2025-03-01', end: '2025-03-31' },
        { label: 'Previous month', start: '2025-02-01', end: '2025-02-28' },
        { label: 'This quarter', start: '2025-01-01', end: '2025-03-31' },
        { label: 'Previous quarter', start: '2024-10-01', end: '2024-12-31' },
        { label: 'This year', start: '2025-01-01', end: '2025-12-31' },
      ],
      weekdays: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun'],
      timezoneLabel: 'UTC+3 (MSK)',
      startDateLabel: '13.03.25',
      endDateLabel: '19.03.25',
      applyLabel: 'Apply',
    },
    columns: ['Date & time', 'Amount', 'Client', 'Operations'],
    transactions: [
      {
        date: '05.08.2025, 19:20',
        amount: '−18 000 ₽',
        amountTone: 'negative',
        bucket: 'agency',
        client: 'Alpha Group',
        operation: 'Charge to client ID4572854289',
      },
      {
        date: '05.08.2025, 17:09',
        amount: '−12 900 ₽',
        amountTone: 'negative',
        bucket: 'agency',
        client: 'SmartMarket',
        operation: 'Charge to client ID4572854289',
      },
      {
        date: '04.08.2025, 11:20',
        amount: '+85 000 ₽',
        amountTone: 'positive',
        bucket: 'wallet',
        client: '—',
        operation: 'Balance top up',
      },
      {
        date: '04.08.2025, 09:06',
        amount: '−9 750 ₽',
        amountTone: 'negative-soft',
        bucket: 'agency',
        client: 'EcoDom',
        operation: 'Charge to client ID4572854289',
      },
      {
        date: '03.08.2025, 11:20',
        amount: '+60 000 ₽',
        amountTone: 'positive',
        bucket: 'wallet',
        client: '—',
        operation: 'Balance top up',
      },
    ],
    loadMoreLabel: 'Load more',
  },
}

const CABINET_ROUTES_RU = [
  { path: '/overview', title: 'Обзор', description: 'Здесь будет обзор кабинета.' },
  { path: '/messages', title: 'Сообщения', description: 'Здесь будет страница сообщений кабинета.' },
  { path: '/clients', title: 'Клиенты', description: 'Здесь будет страница клиентов кабинета.' },
  { path: '/employees', title: 'Сотрудники', description: 'Здесь будет страница сотрудников кабинета.' },
  {
    path: '/demand-analytics',
    title: 'Аналитика спроса',
    description: 'Здесь будет страница аналитики спроса.',
  },
  { path: '/statistics', title: 'Статистика', description: 'Здесь будет страница статистики.' },
  {
    path: '/pro-subscription',
    title: 'Подписка Pro',
    description: 'Здесь будет страница подписки Pro.',
  },
  { path: '/documents', title: 'Документы', description: 'Здесь будет страница документов.' },
  { path: '/wallet', title: 'Кошелёк', description: 'Здесь будет страница кошелька.' },
  { path: '/business', title: 'Для бизнеса', description: 'Здесь будет страница бизнес-инструментов.' },
  {
    path: '/profile',
    title: 'Профиль и настройки',
    description: 'Здесь будет страница профиля и настроек.',
  },
]

const CABINET_ROUTES_EN = [
  { path: '/overview', title: 'Overview', description: 'The overview page will appear here.' },
  { path: '/messages', title: 'Messages', description: 'The messages page will appear here.' },
  { path: '/clients', title: 'Clients', description: 'The clients page will appear here.' },
  { path: '/employees', title: 'Employees', description: 'The employees page will appear here.' },
  {
    path: '/demand-analytics',
    title: 'Demand analytics',
    description: 'The demand analytics page will appear here.',
  },
  { path: '/statistics', title: 'Statistics', description: 'The statistics page will appear here.' },
  {
    path: '/pro-subscription',
    title: 'Pro subscription',
    description: 'The Pro subscription page will appear here.',
  },
  { path: '/documents', title: 'Documents', description: 'The documents page will appear here.' },
  { path: '/wallet', title: 'Wallet', description: 'The wallet page will appear here.' },
  { path: '/business', title: 'For business', description: 'The business tools page will appear here.' },
  {
    path: '/profile',
    title: 'Profile & settings',
    description: 'The profile and settings page will appear here.',
  },
]

export const CABINET_STAGE_CONTENT = CABINET_STAGE_CONTENT_RU
export const CABINET_ROUTES = CABINET_ROUTES_RU

export function getCabinetStageContent(locale = 'ru') {
  return locale === 'en' ? CABINET_STAGE_CONTENT_EN : CABINET_STAGE_CONTENT_RU
}

export function getCabinetRoutes(locale = 'ru') {
  return locale === 'en' ? CABINET_ROUTES_EN : CABINET_ROUTES_RU
}
