import { Primitives } from './primitives'

const flattenPrimitiveTheme = (
  tokens: Record<string, Record<string, string>>,
  prefix = 'primitives',
) =>
  Object.fromEntries(
    Object.entries(tokens).flatMap(([groupName, groupTokens]) =>
      Object.entries(groupTokens).map(([tokenName, value]) => [
        `${prefix}.${groupName}.${tokenName}`,
        value,
      ]),
    ),
  )

export const colorThemes = {
  light: {
    'text.primary': '#000000',
    'text.secondary': '#757575',
    'text.success': '#00a34c',
    'text.error': '#ff4053',
    'text.warning': '#fca400',
    'text.constant.primary': '#000000',
    'text.inverse.primary': '#ffffff',
    'text.inverse.constant.primary': '#ffffff',
    'bg.page': '#ffffff',
    'bg.default': '#f2f1f0',
    'bg.surface': '#f5f5f5',
    'bg.accent': '#f1f6ff',
    'bg.elevation1': '#ffffff',
    'bg.elevation2': '#f7f7f5',
    'bg.success': '#e8f7ee',
    'bg.error': '#fff0f1',
    'bg.warning': '#ffecc9',
    'bg.inverse.elevation1': '#111318',
    'bg.inverse.elevation2': '#1c1f26',
    'bg.inverse.constant.page': '#000000',
    'bg.inverse.constant.default': '#141414',
    'bg.inverse.constant.elevation1': '#1c1c1c',
    'bg.inverse.constant.elevation2': '#242424',
    'backdrop.fill': 'rgba(0, 0, 0, 0.56)',
    'foreground.imageFill': 'rgba(0, 0, 0, 0.32)',
    'border.default': '#ebeae8',
    'border.subtle': 'rgba(18, 24, 38, 0.08)',
    'divider.default': '#ebeae8',
    'components.button.primary': '#1f6fff',
    'components.button.primaryText': '#ffffff',
    'components.control.bg.default': '#f2f1f0',
    'components.control.bg.disabled': '#f2f1f0',
    'components.control.bg.overlay.default': '#ffffff',
    'components.control.bg.overlay.disabled': '#ffffff',
    'components.control.bg.inverse.default': '#262624',
    'components.control.bg.inverse.disabled': '#262624',
    'components.slider.defaultfilled': '#000000',
    'components.bar.defaultfilleddisabled': '#adaca8',
    'components.bar.inverse.defaultfilled': '#ffffff',
    'components.bar.inverse.defaultfilleddisabled': '#878683',
    'components.badge.error': '#ff4a63',
    'components.progress.warning': '#fca400',
    'components.transferFundsVisual.bgGlow': 'rgba(192, 125, 255, 0.28)',
    'components.transferFundsVisual.bgStart': 'rgba(233, 220, 255, 0.92)',
    'components.transferFundsVisual.bgEnd': 'rgba(243, 238, 252, 0.96)',
    'components.transferFundsVisual.baseStart': '#b27cff',
    'components.transferFundsVisual.baseEnd': '#8e4dff',
    'components.transferFundsVisual.highlightStrong': 'rgba(255, 255, 255, 0.72)',
    'components.transferFundsVisual.highlight': 'rgba(255, 255, 255, 0.18)',
    'components.transferFundsVisual.highlightBorder': 'rgba(255, 255, 255, 0.22)',
    'components.transferFundsVisual.coinText': '#8a41ff',
    'components.transferFundsVisual.coinStart': 'rgba(226, 188, 255, 0.98)',
    'components.transferFundsVisual.coinEnd': 'rgba(196, 131, 255, 0.96)',
    'components.transferFundsVisual.coinBorder': 'rgba(138, 65, 255, 0.2)',
    'components.promoVisual.shirtStart': '#ffd4dc',
    'components.promoVisual.shirtMiddle': '#f6f1ff',
    'components.promoVisual.shirtEnd': '#d2f2ff',
    'components.promoVisual.checkStart': '#d7f5ff',
    'components.promoVisual.checkEnd': '#b5e0ff',
    'components.promoVisual.checkText': '#1274b4',
    'components.adsMeta.locationStart': '#2891ff',
    'components.adsMeta.locationEnd': '#135de6',
    'components.adPreview.defaultStart': '#ece7e1',
    'components.adPreview.defaultEnd': '#ddd7d0',
    'components.adPreview.sheen': 'rgba(255, 255, 255, 0.48)',
    'components.adPreview.dot': 'rgba(255, 255, 255, 0.74)',
    'components.adPreview.mintStart': '#f1eee9',
    'components.adPreview.mintEnd': '#ddd8d1',
    'components.adPreview.sandStart': '#f2efeb',
    'components.adPreview.sandEnd': '#ddd8d0',
    'components.adPreview.roseStart': '#f4ebeb',
    'components.adPreview.roseEnd': '#ded8d7',
    'components.adPreview.skyStart': '#eff4f7',
    'components.adPreview.skyEnd': '#dbe1e8',
  },
  dark: {
    'text.primary': '#ffffff',
    'text.secondary': '#a3a3a3',
    'text.success': '#45c777',
    'text.error': '#ff6474',
    'text.warning': '#ffc04d',
    'text.constant.primary': '#000000',
    'text.inverse.primary': '#000000',
    'text.inverse.constant.primary': '#ffffff',
    'bg.page': '#111318',
    'bg.default': '#21252d',
    'bg.surface': '#111318',
    'bg.accent': '#171b24',
    'bg.elevation1': '#171a20',
    'bg.elevation2': '#1c1f26',
    'bg.success': '#10351f',
    'bg.error': '#3a151b',
    'bg.warning': '#3b2a08',
    'bg.inverse.elevation1': '#ffffff',
    'bg.inverse.elevation2': '#f7f7f5',
    'bg.inverse.constant.page': '#000000',
    'bg.inverse.constant.default': '#141414',
    'bg.inverse.constant.elevation1': '#1c1c1c',
    'bg.inverse.constant.elevation2': '#242424',
    'backdrop.fill': 'rgba(0, 0, 0, 0.72)',
    'foreground.imageFill': 'rgba(0, 0, 0, 0.48)',
    'border.default': 'rgba(255, 255, 255, 0.08)',
    'border.subtle': 'rgba(255, 255, 255, 0.08)',
    'divider.default': 'rgba(255, 255, 255, 0.08)',
    'components.button.primary': '#5aa8ff',
    'components.button.primaryText': '#000000',
    'components.control.bg.default': '#21252d',
    'components.control.bg.disabled': '#21252d',
    'components.control.bg.overlay.default': '#171a20',
    'components.control.bg.overlay.disabled': '#171a20',
    'components.control.bg.inverse.default': '#262624',
    'components.control.bg.inverse.disabled': '#262624',
    'components.slider.defaultfilled': '#ffffff',
    'components.bar.defaultfilleddisabled': '#63625f',
    'components.bar.inverse.defaultfilled': '#ffffff',
    'components.bar.inverse.defaultfilleddisabled': '#878683',
    'components.badge.error': '#ff6474',
    'components.progress.warning': '#ffc04d',
    'components.transferFundsVisual.bgGlow': 'rgba(192, 125, 255, 0.28)',
    'components.transferFundsVisual.bgStart': 'rgba(233, 220, 255, 0.92)',
    'components.transferFundsVisual.bgEnd': 'rgba(243, 238, 252, 0.96)',
    'components.transferFundsVisual.baseStart': '#b27cff',
    'components.transferFundsVisual.baseEnd': '#8e4dff',
    'components.transferFundsVisual.highlightStrong': 'rgba(255, 255, 255, 0.72)',
    'components.transferFundsVisual.highlight': 'rgba(255, 255, 255, 0.18)',
    'components.transferFundsVisual.highlightBorder': 'rgba(255, 255, 255, 0.22)',
    'components.transferFundsVisual.coinText': '#8a41ff',
    'components.transferFundsVisual.coinStart': 'rgba(226, 188, 255, 0.98)',
    'components.transferFundsVisual.coinEnd': 'rgba(196, 131, 255, 0.96)',
    'components.transferFundsVisual.coinBorder': 'rgba(138, 65, 255, 0.2)',
    'components.promoVisual.shirtStart': '#ffd4dc',
    'components.promoVisual.shirtMiddle': '#f6f1ff',
    'components.promoVisual.shirtEnd': '#d2f2ff',
    'components.promoVisual.checkStart': '#d7f5ff',
    'components.promoVisual.checkEnd': '#b5e0ff',
    'components.promoVisual.checkText': '#1274b4',
    'components.adsMeta.locationStart': '#2891ff',
    'components.adsMeta.locationEnd': '#135de6',
    'components.adPreview.defaultStart': '#ece7e1',
    'components.adPreview.defaultEnd': '#ddd7d0',
    'components.adPreview.sheen': 'rgba(255, 255, 255, 0.48)',
    'components.adPreview.dot': 'rgba(255, 255, 255, 0.74)',
    'components.adPreview.mintStart': '#f1eee9',
    'components.adPreview.mintEnd': '#ddd8d1',
    'components.adPreview.sandStart': '#f2efeb',
    'components.adPreview.sandEnd': '#ddd8d0',
    'components.adPreview.roseStart': '#f4ebeb',
    'components.adPreview.roseEnd': '#ded8d7',
    'components.adPreview.skyStart': '#eff4f7',
    'components.adPreview.skyEnd': '#dbe1e8',
  },
} as const

export type ColorThemeName = keyof typeof colorThemes
export type ColorTheme = (typeof colorThemes)[ColorThemeName]

export const primitiveColorThemes = {
  light: flattenPrimitiveTheme(Primitives.light),
  dark: flattenPrimitiveTheme(Primitives.dark),
  alpha: flattenPrimitiveTheme(Primitives.alpha, 'primitives.alpha'),
} as const

export type PrimitiveColorTheme = typeof primitiveColorThemes
